global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "healthcheck-django"
    metrics_path: /metrics
    static_configs:
      - targets:
          - healthcheck-web:8000

  - job_name: "healthcheck-flower"
    metrics_path: /metrics
    static_configs:
      - targets:
          - healthcheck-flower-server:8001