# Generated by Django 6.0.2 on 2026-02-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "CNP",
                    models.CharField(
                        help_text="Cod Numeric Personal", max_length=13, unique=True
                    ),
                ),
                ("nume", models.CharField(help_text="Last name", max_length=100)),
                ("prenume", models.CharField(help_text="First name", max_length=100)),
                ("data_nasterii", models.DateField(help_text="Date of birth")),
                (
                    "serie_ci",
                    models.CharField(help_text="ID card series", max_length=10),
                ),
                (
                    "numar_ci",
                    models.CharField(help_text="ID card number", max_length=20),
                ),
                (
                    "nationalitate",
                    models.CharField(
                        default="Română", help_text="Nationality", max_length=50
                    ),
                ),
                (
                    "telefon",
                    models.CharField(
                        blank=True, help_text="Phone number", max_length=20, null=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Email address", max_length=254, null=True
                    ),
                ),
                ("oras", models.CharField(help_text="City", max_length=100)),
                ("judet", models.CharField(help_text="County", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
                "db_table": "patients",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["CNP"], name="patients_CNP_da8705_idx"),
                    models.Index(
                        fields=["nume", "prenume"], name="patients_nume_f81109_idx"
                    ),
                ],
            },
        ),
    ]
