# Generated by Django 6.0.1 on 2026-03-03 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubsub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='CNP',
            field=models.CharField(help_text='Cod Numeric Personal (13 digits)', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='CNP-ul trebuie să aibă exact 13 cifre', regex='^\\d{13}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='numar_ci',
            field=models.CharField(help_text='ID card number (6 digits)', max_length=6, validators=[django.core.validators.RegexValidator(message='Număr CI trebuie să aibă exact 6 cifre', regex='^\\d{6}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='serie_ci',
            field=models.CharField(help_text='ID card series (2 uppercase letters)', max_length=2, validators=[django.core.validators.RegexValidator(message='Serie CI trebuie să aibă exact 2 litere majuscule', regex='^[A-Z]{2}$')]),
        ),
    ]
