# Generated by Django 6.0.1 on 2026-03-03 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubsub', '0003_userprofile_accesslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address', max_length=254, null=True, validators=[django.core.validators.RegexValidator(message='Introduceți o adresă de email validă', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='telefon',
            field=models.CharField(blank=True, help_text='Phone number in international format (e.g., +40712345678)', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Introduceți un număr de telefon valid în format internațional (ex: +40712345678)', regex='^\\+?[1-9]\\d{1,14}$')]),
        ),
    ]
