# Generated by Django 6.0.1 on 2026-03-03 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubsub', '0004_alter_patient_email_alter_patient_telefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='telefon',
            field=models.CharField(blank=True, help_text='Phone number in international format (e.g., +40712345678)', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Introduceți un număr de telefon valid în format internațional (ex: +40712345678)', regex='^(\\+?[1-9]\\d{1,14}|0\\d{9,14})$')]),
        ),
    ]
