# Generated by Django 6.0.1 on 2026-05-20 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubsub', '0009_add_pseudonym'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['pseudonym'], name='patients_pseudon_66dbec_idx'),
        ),
    ]
