# Generated by Django 6.0.1 on 2026-04-28 15:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pubsub', '0006_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientClinicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Female'), (1, 'Male')], help_text='Gender encoded as 0 = Female, 1 = Male', null=True)),
                ('age_years', models.PositiveSmallIntegerField(blank=True, help_text='Age in years', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('hypertension', models.BooleanField(blank=True, null=True)),
                ('heart_disease', models.BooleanField(blank=True, null=True)),
                ('smoking_history', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Never'), (1, 'No info'), (2, 'Former / Ever / Not current'), (3, 'Current')], help_text='Ordinal smoking history used by the Mustafa model', null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('hba1c_level', models.DecimalField(blank=True, decimal_places=2, help_text='HbA1c level', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('20'))])),
                ('blood_glucose_level', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('high_bp', models.BooleanField(blank=True, null=True)),
                ('high_chol', models.BooleanField(blank=True, null=True)),
                ('chol_check', models.BooleanField(blank=True, null=True)),
                ('smoker', models.BooleanField(blank=True, null=True)),
                ('stroke', models.BooleanField(blank=True, null=True)),
                ('phys_activity', models.BooleanField(blank=True, null=True)),
                ('fruits', models.BooleanField(blank=True, null=True)),
                ('veggies', models.BooleanField(blank=True, null=True)),
                ('heavy_alcohol_consumption', models.BooleanField(blank=True, null=True)),
                ('any_healthcare', models.BooleanField(blank=True, null=True)),
                ('no_docbc_cost', models.BooleanField(blank=True, null=True)),
                ('general_health', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Excellent'), (2, 'Very good'), (3, 'Good'), (4, 'Fair'), (5, 'Poor')], null=True)),
                ('mental_health_days', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('physical_health_days', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('diff_walk', models.BooleanField(blank=True, null=True)),
                ('education', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Less than 9th grade'), (2, 'High school graduate'), (3, 'Some college'), (4, 'College graduate'), (5, 'Post-graduate'), (6, 'Other / Unknown')], null=True)),
                ('income', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Less than $10,000'), (2, '$10,000 to $14,999'), (3, '$15,000 to $19,999'), (4, '$20,000 to $24,999'), (5, '$25,000 to $34,999'), (6, '$35,000 to $49,999'), (7, '$50,000 to $74,999'), (8, '$75,000 or more')], null=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_records', to='pubsub.patient')),
            ],
            options={
                'verbose_name': 'Patient Clinical Record',
                'verbose_name_plural': 'Patient Clinical Records',
                'db_table': 'patient_clinical_records',
                'ordering': ['-recorded_at', '-id'],
                'indexes': [models.Index(fields=['patient', 'recorded_at'], name='patient_cli_patient_f86f9d_idx')],
            },
        ),
    ]
