# Generated by Django 6.0.1 on 2026-04-28 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_ai', '0001_initial'),
        ('pubsub', '0006_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientclinicalrecord',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_record', to='pubsub.patient'),
        ),
    ]
