# Generated by Django 6.0.1 on 2026-05-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_ai', '0002_alter_patientclinicalrecord_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientclinicalrecord',
            name='data_consent_for_training',
            field=models.BooleanField(default=False, help_text='Whether the patient consented to use this data in federated training.'),
        ),
        migrations.AddField(
            model_name='patientclinicalrecord',
            name='diabetes_status',
            field=models.CharField(choices=[('has', 'Confirmed diabetes'), ('has_not', 'Confirmed no diabetes'), ('not_confirmed', 'Not confirmed')], default='not_confirmed', help_text='Confirmed diabetes diagnosis status used as the federated label.', max_length=20),
        ),
    ]
