# Generated by Django 6.0.1 on 2026-05-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_ai', '0003_patientclinicalrecord_diabetes_status_and_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientclinicalrecord',
            name='education',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Less than 9th grade'), (2, 'High school graduate'), (3, 'Attended college (no degree)'), (4, 'College graduate'), (5, 'Post-graduate'), (6, 'Other / Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='patientclinicalrecord',
            name='smoking_history',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Never'), (1, 'No info'), (2, 'Former'), (3, 'Current')], help_text='Ordinal smoking history used by the Mustafa model', null=True),
        ),
    ]
