# Generated by Django 6.0.1 on 2026-05-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_ai', '0004_alter_patientclinicalrecord_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientclinicalrecord',
            name='federated_train_count',
            field=models.PositiveIntegerField(default=0, help_text='How many federated rounds have used this record for local training.'),
        ),
        migrations.AddField(
            model_name='patientclinicalrecord',
            name='last_federated_train_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last used in federated local training.', null=True),
        ),
    ]
